services:
  postgres:
  # Local PostgreSQL for development and testing
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecoplus
    ports:
      - "5432:5432"
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d
      # - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  grafana:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000/tcp
    depends_on:
      - postgres
    # volumes:
    #   - dashboard_data:/var/lib/grafana
    networks:
      - app-network

# volumes:
#   db_data:
#   dashboard_data:

networks:
  app-network:
    driver: bridge
