services:
  grafana:
    build:
      context: ./
      dockerfile: Dockerfile
    # image: ghcr.io/ecomais/ecoplus-dashboard:latest
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
    ports:
      - 3000:3000/tcp
    volumes:
      - ./provisioning:/etc/grafana/provisioning
