name: Docker Hub Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ecomais/ecoplus-dashboard
  TAG_LATEST: latest
  TAG_VERSION: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            docker.io/${{ env.IMAGE_NAME }}:${{ env.TAG_LATEST }}
            docker.io/${{ env.IMAGE_NAME }}:${{ env.TAG_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
